#ansible n1 -m file -a "path=/home/fedora/n1_dir state=directory
---
- name: Update n1 servers
  hosts: n1

  tasks:
   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory
...

