---

- name: Update n1 servers
  hosts: n1

  tasks:
   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory

   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory

- name: Update n2 servers
  hosts: n2

  tasks:
   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory

- name: Update n6 servers
  hosts: n6

  tasks:
   - name: ensure /var/www/html exists
     file:
       path: /var/www/html
       state: directory 

     file:
       path: /home/fedora/new_dir
       state: directory      
  

- name: Update group1 servers
  hosts: g1

  tasks:
   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory
...

