---
- name: Update n1 servers
  hosts: n1

  tasks:
   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory

   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory

- name: Update n2 servers
  hosts: n2

  tasks:
   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory

- name: Update n3 servers
  hosts: n3

  tasks:
   - name: Debug host information
     debug:
       msg: 'Creating /var/www/html on {n3}'

   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory      

- name: Update group1 servers
  hosts: g1

  tasks:
   - name: Create Directory
     file:
       path: /home/fedora/new_dir
       state: directory
...

